// Copies the icons the app uses out of @hackernoon/pixel-icon-library into
// src/lib/icons/paths.ts, so nothing under node_modules is touched at
// runtime and the library stays a devDependency.
//
//   pnpm run icons
//
// Every icon in the library sits on a 24x24 grid and is drawn with <path>,
// <polygon> and <rect> elements. This script folds each icon into one path
// string (polygons and rects become "M ... Z" subpaths), drops any fill
// attribute so the SVG inherits currentColor, skips the invisible
// fill="none" background rects some solid icons carry, and refuses anything
// that is not on the 24 grid or carries a transform.

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const source = join(
  root,
  "node_modules/@hackernoon/pixel-icon-library/icons/SVG",
);
const target = join(root, "src/lib/icons/paths.ts");

// Library file name, keyed by the name the app uses. Keep the two the same
// unless the library name is awkward; today they all match.
const ICONS = {
  search: "regular/search",
  heart: "regular/heart",
  "heart-solid": "solid/heart-solid",
  star: "regular/star",
  "star-solid": "solid/star-solid",
  home: "regular/home",
  grid: "regular/grid",
  user: "regular/user",
  logout: "regular/logout",
  envelope: "regular/envelope",
  check: "regular/check",
  play: "regular/play",
  "window-close": "regular/window-close",
  "check-list-solid": "solid/check-list-solid",
  "chart-line": "regular/chart-line",
  "exclamation-triangle": "regular/exclamation-triangle",
};

const attr = (tag, name) => {
  const match = tag.match(new RegExp(`\\b${name}="([^"]*)"`));
  return match ? match[1] : undefined;
};

const number = (value, file) => {
  const n = Number(value);
  if (!Number.isInteger(n)) {
    throw new Error(
      `${file}: "${value}" is not an integer, icon is off the pixel grid`,
    );
  }
  return n;
};

function toSubpath(tag, file) {
  if (attr(tag, "fill") === "none") return "";
  if (attr(tag, "transform"))
    throw new Error(`${file}: transforms are not supported`);

  if (tag.startsWith("<path")) {
    // The first moveto of a path is absolute even when written as "m".
    // Once several paths are folded into one string that stops being true,
    // so promote it to "M" before joining.
    return (attr(tag, "d") ?? "").replace(/^\s*m/, "M");
  }
  if (tag.startsWith("<polygon")) {
    const points = attr(tag, "points")
      .trim()
      .split(/[\s,]+/)
      .map((v) => number(v, file));
    const pairs = [];
    for (let i = 0; i < points.length; i += 2)
      pairs.push(`${points[i]} ${points[i + 1]}`);
    return `M${pairs.join("L")}Z`;
  }
  if (tag.startsWith("<rect")) {
    const x = number(attr(tag, "x") ?? "0", file);
    const y = number(attr(tag, "y") ?? "0", file);
    const w = number(attr(tag, "width"), file);
    const h = number(attr(tag, "height"), file);
    return `M${x} ${y}h${w}v${h}h${-w}Z`;
  }
  throw new Error(`${file}: unexpected element ${tag.slice(0, 20)}`);
}

function extract(file) {
  const svg = readFileSync(join(source, `${file}.svg`), "utf8");
  if (!svg.includes('viewBox="0 0 24 24"'))
    throw new Error(`${file}: not on the 24 grid`);
  const tags = svg.match(/<(path|polygon|rect)\b[^>]*>/g) ?? [];
  const d = tags
    .map((tag) => toSubpath(tag, file))
    .filter(Boolean)
    .join("");
  if (!d) throw new Error(`${file}: no drawable elements`);
  return d;
}

const entries = Object.entries(ICONS).map(
  ([name, file]) => `  "${name}": "${extract(file)}",`,
);

const out = `// Generated by scripts/extract-icons.mjs from @hackernoon/pixel-icon-library
// (MIT, https://github.com/hackernoon/pixel-icon-library). Do not edit by
// hand; add the icon to the script's list and run \`pnpm run icons\`.
//
// Every path draws on a 24x24 grid with integer moves only.

export const ICON_PATHS = {
${entries.join("\n")}
} as const;

export type IconName = keyof typeof ICON_PATHS;
`;

writeFileSync(target, out);
console.log(`wrote ${Object.keys(ICONS).length} icons to ${target}`);
